version: '3.3'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

  node:
    container_name: nent-tech-trainee
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.production
    ports:
      - '80:3000'
    links:
      - mongo