FROM node:12-alpine
WORKDIR /src/NE-rest-back/
ENV NODE_ENV=dev
ENV RUN=docker
COPY package*.json ./
RUN npm install && npm install -g mocha
COPY . .
EXPOSE 3000
CMD ["mocha", "tests/restaurants.test.js", "--exit"]